name: Sync iOS Rules

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: blackmatrix7/ios_rule_script
        path: ios_rule_script

    - name: Checkout your repository
      uses: actions/checkout@v2
      with:
        path: repo

    - name: Sync rules
      run: |
        cp -r ios_rule_script/rule/* repo/rule/
      
    - name: Commit and push changes
      run: |
        cd repo
        git config --global user.name 'GitHub Acitons'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m 'Daily sync of iOS rules'
        git push
