name: Sync Rules

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: blackmatrix7/ios_rule_script
        path: ios_rule_script

    - name: Checkout your repository
      uses: actions/checkout@v2
      with:
        path: my_repo

    - name: Sync rules
      run: |
        mkdir -p my_repo/rule  # 创建目标文件夹，如果不存在
        cp -r ios_rule_script/rule/* my_repo/rule/
      
    - name: Commit and push changes
      run: |
        cd my_repo
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'Actions@GitHub.com'
        git add .
        git commit -m 'Daily sync of rules'
        git push
