name: Daily sync
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Rules repository
      uses: actions/checkout@v2
      with:
        repository: blackmatrix7/ios_rule_script
        path: rules

    - name: Checkout Rewrites repository
      uses: actions/checkout@v2
      with:
        repository: RuCu6/QuanX
        path: rewrites

    - name: Checkout Scripts repository
      uses: actions/checkout@v2
      with:
        repository: RuCu6/QuanX
        path: scripts

    - name: Sync iOS rules
      run: |
        mkdir -p repo/rules  # 创建目标文件夹 "rules"，如果不存在
        cp -r rules/rule/* repo/rules/  # 注意这里的路径也相应调整
      
    - name: Sync QuanX Rewrites
      run: |
        mkdir -p repo/rewrites  # 创建目标文件夹 "rewrites"，如果不存在
        cp -r rewrites/* repo/rewrites/  # 同样，路径调整为 rewrites
      
    - name: Sync QuanX Scripts
      run: |
        mkdir -p repo/scripts  # 创建目标文件夹 "scripts"，如果不存在
        cp -r scripts/* repo/scripts/  # 同样，路径调整为 scripts
      
    - name: Commit and push changes
      run: |
        cd repo
        git config --global user.name 'your-username'
        git config --global user.email 'your-email@example.com'
        git add .
        git commit -m 'Daily sync'
        git push
