name: Sync Rules

on:
  schedule:
    - cron: '0 10 * * *' # 每天10点
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: blackmatrix7/ios_rule_script
        path: source-repo

    - name: Sync rules
      run: |
        mkdir -p ./rule # 确保目标文件夹存在
        cp -r ./source-repo/rule/* ./rule # 复制源文件夹内容到目标文件夹

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Sync rules"
        git push
